name: Build and Push to Nuget

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v3
 
    - name: setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: install mjml
      run: |
        npm i mjml -g

    - name: test
      run: |
        dotnet test --filter Category!=Dependencies

    - name: pack
      run: |
        cd Mjml.Net & dotnet pack -c Release

    - name: publish
      if: github.event_name != 'pull_request' && github.ref_name == 'main'
      run: |
        dotnet nuget push **/*.nupkg --source 'https://api.nuget.org/v3/index.json' --skip-duplicate -k ${{ secrets.nuget }} 
